name: Build Docker Image
on: [push]

jobs:
  k8s:
    name: RemoteDockerImage
    runs-on: ubuntu-latest
    steps:
      - id: rethinkdb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            repository: rethinkdb/rethinkdb-dockerfiles
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./init/
          push: true
          file: ./init/Dockerfile
          build-args: |
            upstream_image=rethinkdb:${{ steps.rethinkdb.outputs.release }}
          tags: pozetroninc/rethinkdb-cluster:latest, pozetroninc/rethinkdb-cluster:${{ steps.rethinkdb.outputs.release }}
